name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get new commits
        id: get_commits
        run: echo "::set-output name=new_commit_count::$(git log --oneline --since '24 hours ago' | wc -l)"
  release:
    needs: check-release
    uses: ./.github/workflows/release.yml
    if: ${{ needs.check-release.outputs.new_commit_count > 0 }}